### ISSUE TITLE
double precision

### ISSUE THREAD

**Issue by RallyTronics** [xissburg/edyn#105]
When I select double precision in cmake ( i use cmake-gui ), the build_settings.h file does not appear to be correct:

```
#ifndef EDYN_BUILD_SETTINGS_H
#define EDYN_BUILD_SETTINGS_H

/* #undef EDYN_DOUBLE_PRECISION */

#endif // EDYN_BUILD_SETTINGS_H

```
If I change it to 
`#define EDYN_DOUBLE_PRECISION 1`
it appears to work correctly

**Comment by xissburg** [comment]
I should've being using `#ifdef EDYN_DOUBLE_PRECISION` instead of `#if` in the definition of `edyn::scalar`. Thanks for catching this one.
