### ISSUE TITLE
registry_operation does not preserve the order of operations in async mode compared to the same operations in sync

### ISSUE THREAD

**Issue by volcoma** [xissburg/edyn#126]
So when using async mode the registry_operation does the operations with same type sequentially 
which does not correspond to the sync mode

```
for (auto &op : emplace_components) {
            op->execute(registry, entity_map);
        }

        for (auto &op : replace_components) {
            op->execute(registry, entity_map);
        }

        for (auto &op : remove_components) {
            op->execute(registry, entity_map);
        }
```
for example

```
   // these 3 operations will trigger after the operations below which is not the same behavior
   
   
    registry.remove<graph_node>(entity);
    registry.remove<multi_island_resident>(entity);
    registry.remove<island_resident>(entity);



    // Insert rigid body as a node in the entity graph.
    auto non_connecting = def.kind != rigidbody_kind::rb_dynamic;
    auto node_index = registry.ctx().get<entity_graph>().insert_node(entity, non_connecting);
    registry.emplace_or_replace<graph_node>(entity, node_index);
    if(def.kind == rigidbody_kind::rb_dynamic)
    {
        registry.emplace_or_replace<island_resident>(entity);
    }
    else
    {
        registry.emplace_or_replace<multi_island_resident>(entity);
    }
```
i believe the actions should be in one container or somehow preserve the order in which they occurred. 
Not doing so would result in virtually impossible modification of properties of rigidbody at runtime for example changing the kind

Changing properties of a rigidbody at runtime should be possible.
Also there should be some way of "unmaking"a rigidbody i.e removing all the components that edyn adds, because there are a lot of internal tag components that it adds behind the scenes which are pretty hard to chase.

**Comment by xissburg** [comment]
The registry operation is not very sophisticated as it stands. It's a difficult problem to tackle with an elegant solution. It works correctly in all my use cases so far, but I can see where it will result in unexpected behavior. It's currently a quite simple and efficient data structure. To correctly replicate all changes from one registry to another, a more complex history of changes would have to be recorded. That means a new data structure would have to be designed. This needs some brainstorming...

**Comment by xissburg** [comment]
Closed via https://github.com/xissburg/edyn/pull/132
