### ISSUE TITLE
Facing multiple compiler errors on MSYS2 Clang (64-bit)

### ISSUE THREAD

**Issue by yogwoggf** [xissburg/edyn#136]
I'm facing these specific errors across all of edyn when building:

- `error: no matching function for call to 'min'`
    - ![image](https://github.com/user-attachments/assets/67af5298-1a25-4b9a-afc9-6af1811508bc) 
https://github.com/xissburg/edyn/blob/83ab7917e55c2a6f546af97c1a8c0dc5bdd71abd/include/edyn/replication/registry_operation_builder.hpp#L26-L31
- `Missing template arguments, all candidates have non-deducible template parameters`
    - ![image](https://github.com/user-attachments/assets/6f665bfd-7e1f-4854-90da-8c063195977a)
https://github.com/xissburg/edyn/blob/83ab7917e55c2a6f546af97c1a8c0dc5bdd71abd/include/edyn/replication/registry_operation_builder.hpp#L36-L38

I've used MSYS2 Clang and the one that comes with Visual Studio 2022. (GNU-like cmdline)
I'd appreciate some general advice on how to figure this out, not sure if its a real bug or a known compiler-related issue.

**Comment by xissburg** [comment]
On the first issue, I can't tell where the confusion comes from. The compiler is pulling a non-sensical `unsigned long long` from somewhere even though the types are clearly and consistently specified. You could try using some extra verbosity and casting to force the types to be `unsigned long`. Let me know what works for you and I can make the change official in a later commit.

The second issue must be that it should be `std::forward<Args>(args)...` instead. I have pushed a change. Let me know if that fixes the issue.

**Comment by yogwoggf** [comment]
> On the first issue, I can't tell where the confusion comes from. The compiler is pulling a non-sensical `unsigned long long` from somewhere even though the types are clearly and consistently specified. You could try using some extra verbosity and casting to force the types to be `unsigned long`. Let me know what works for you and I can make the change official in a later commit.
> 
> The second issue must be that it should be `std::forward<Args>(args)...` instead. I have pushed a change. Let me know if that fixes the issue.

Great news, so as you observed the first issue was more or less a compiler issue. Somewhere between when I made the issue and today, the compiler resolved that issue on its own. The second issue is also fixed, and edyn now compiles successfully 👍
