### ISSUE TITLE
[Proposal] Godot Engine

### ISSUE THREAD

**Issue by nonunknown** [xissburg/edyn#2]
Hi I'm a godot engine user, the devs posted that they need someone (for hire) to rewrite physics engine:

https://www.reddit.com/r/godot/comments/hqhxcm/lets_talk_about_the_actual_approach_for_move_and/ (see reduzio answer)

I was thinking if you can help them, since the head developer is focused on vulkan.

**Comment by xissburg** [comment]
Hi, I'm not currently a Godot user. This physics engine is still in an early stage and it is not going to be written for Godot. It is intended to be the physics engine of choice for `EnTT` users and it has a focus on multithreaded, networked and distributed physics simulation of large worlds. If there is a way to use `EnTT` inside Godot then it might be possible to do an integration.
