### ISSUE TITLE
Missing `SIZE_MAX` definition on linux environment

### ISSUE THREAD

**Issue by jcbecker** [xissburg/edyn#3]
Error log:
```
{PATH}...edyn/include/edyn/math/geom.hpp:178:24: error: ‘SIZE_MAX’ was not declared in this scope
  178 |     auto closest_idx = SIZE_MAX;
```
compiler: g++ 10.1.0

There is a definition for this macro on the header file of the standard library(cstdint), adding `#include <cstdint>` on the file `edyn/include/edyn/math/geom.hpp` works just fine for me.

But I don't know which version of the standard library you're using or if you're setting this macro to another value.

**Comment by xissburg** [comment]
Thanks for opening the issue. I have added some extra `#include`s which hopefully fixes it.
