### ISSUE TITLE
Compile VS2019 issue

### ISSUE THREAD

**Issue by RobertMassart** [xissburg/edyn#61]
[UE4-EdynBuildErrors.txt](https://github.com/xissburg/edyn/files/7437112/UE4-EdynBuildErrors.txt)

These two warnings probably don't matter
1>D:/UE500/TestEdynPhysics/Plugins/PeernetDeterministicPhysics/Source/PeernetDeterministicPhysics/Private/edyn/parallel/island_worker.cpp(59): warning C5038: data member 'edyn::island_worker::m_splitting' will be initialized after data member 'edyn::island_worker::m_state'
1>D:/UE500/TestEdynPhysics/Plugins/PeernetDeterministicPhysics/Source/PeernetDeterministicPhysics/Private/edyn/parallel/island_worker.cpp(60): warning C5038: data member 'edyn::island_worker::m_state' will be initialized after data member 'edyn::island_worker::m_bphase'

But don't understand how to fix the following error:
1>D:\UE500\TestEdynPhysics\Plugins\PeernetDeterministicPhysics\Source\PeernetDeterministicPhysics\Public\entt\entity\storage.hpp(246): error C2512: 'edyn::multi_island_resident': no appropriate default constructor available
1>  D:\UE500\TestEdynPhysics\Plugins\PeernetDeterministicPhysics\Source\PeernetDeterministicPhysics\Public\entt\entity\storage.hpp(246): note: Invalid aggregate initialization

**Comment by xissburg** [comment]
I have just built it successfully in VS2019. Please reopen this issue if you have any further info.
