### ISSUE TITLE
Build fail due to entt dependency (manjaro)

### ISSUE THREAD

**Issue by tree786** [xissburg/edyn#63]
Hola , 

I'd like to try compile this on my arch distro, but I get error like this when try to run `cmake ..`:
```
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindEnTT.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "EnTT", but
  CMake did not find one.

  Could not find a package configuration file provided by "EnTT" with any of
  the following names:

    EnTTConfig.cmake
    entt-config.cmake

  Add the installation prefix of "EnTT" to CMAKE_PREFIX_PATH or set
  "EnTT_DIR" to a directory containing one of the above files.  If "EnTT"
  provides a separate development package or SDK, be sure it has been
  installed.
```

How would i install entt so that is recognizes xissburg?

Gracias

**Comment by xissburg** [comment]
Did you run `conan install ..` as per the build instructions?

**Comment by tree786** [comment]
Yep, I ran that in the `build` folder, but it did nothing. This is what I get when I run `conan install ..`:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (edyn/0.2.0): Installing package
Requirements
    entt/3.8.0 from 'conancenter' - Cache
Packages
    entt/3.8.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
entt/3.8.0: Already installed!
conanfile.py (edyn/0.2.0): Generator txt created conanbuildinfo.txt
conanfile.py (edyn/0.2.0): Generator cmake created conanbuildinfo.cmake
conanfile.py (edyn/0.2.0): Generator cmake_find_package created FindEnTT.cmake
conanfile.py (edyn/0.2.0): Aggregating env generators
conanfile.py (edyn/0.2.0): Generated conaninfo.txt
conanfile.py (edyn/0.2.0): Generated graphinfo
```
But still get the build error when I then run `cmake ..`

**Comment by xissburg** [comment]
I imagine you have a `FindEnTT.cmake` in the build folder. Could you try adding the build folder to `CMAKE_MODULE_PATH`, e.g. `cmake -DCMAKE_MODULE_PATH=build ..`. Perhaps try it with the full absolute path to the `build` folder.

**Comment by tree786** [comment]
Hmm I am quite confused. I have `FindEnTT.cmake` in my `build` folder like you said, but i not know how to set full path to build folder in cmake (i quite new to cmake). Does it have to be something like this:
```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "./build")
```

**Comment by xissburg** [comment]
If you're using CMake GUI you can add a `CMAKE_MODULE_PATH` variable and assign the path to the build folder. Or you can do it in the command line. While in the build folder, do `cmake -DCMAKE_MODULE_PATH=build ..`.

**Comment by tree786** [comment]
Ok i see, I have run the command `cmake -DCMAKE_MODULE_PATH=build ..` inside `build` folder, but I still get the same error:
![issue](https://user-images.githubusercontent.com/40580296/142260763-5d8e3470-49f1-405f-9b14-928a46e1eb27.png)

**Comment by xissburg** [comment]
Can you try `cmake -DCMAKE_MODULE_PATH=/home/mm/Desktop/edyn/build ..`? I.e. the full absolute path to the build folder.

**Comment by tree786** [comment]
>Can you try cmake -DCMAKE_MODULE_PATH=/home/mm/Desktop/edyn/build ..? I.e. the full absolute path to the build folder.
>
Superb, that works now ! Thanks much !

**Comment by xissburg** [comment]
Yeah but this should not be necessary. The conanfile.txt was recently replaced by a conanfile.py and it seems it has some issue, which I am trying to figure out.
