### ISSUE TITLE
entt version is out of date for edyn

### ISSUE THREAD

**Issue by nneesshh** [xissburg/edyn#67]
hi, big guy. the entt version is out of date for edyn.
I compile failed either with the latest entt, or the fork in you repository.

can you update  edyn to the latest version entt ?

many thanks

**Comment by xissburg** [comment]
Edyn uses Conan to install the supported version of EnTT, which is 3.8.0, which is not the latest (see the readme on how to build it using Conan). It will not be updated to support the latest version just yet. I am not sure how much work would be needed, perhaps not much. You can fork this project and try updating to support the latest EnTT and then submit a pull request if you want and I will have a look.

**Comment by nneesshh** [comment]
yes, 3.8.0 work right on windows. thanks for your reply, you are really nice guy. The template is too hard for me to read, I just can't do this hard work by now. The hope is still all on you, Orz
