### ISSUE TITLE
How do I contact you?

### ISSUE THREAD

**Issue by i-make-robots** [xissburg/edyn#68]
I liked your toptal posts about programming physics.  I need someone to write a physics engine.  the top tal link takes me to a survey instead of the "hire xissburg" page.  after the fifth question I gave up.  So my issue is I can't figure out how to throw money at you and get physics in return.  Please contact me back.  Thank you!

**Comment by xissburg** [comment]
Hi, Edyn is the physics engine I've been working on right now. What kind of physics engine are you thinking about building? You can contact me directly at xissburg at xissburg dot com.
