### ISSUE TITLE
Is anyone able to build this in VS2019?

### ISSUE THREAD

**Issue by RallyTronics** [xissburg/edyn#7]
I am getting a large number of build errors.

**Comment by xissburg** [comment]
I haven't tried building in Windows yet. I'll have to look into this later and also make sure the testbed project builds together with Bgfx.

**Comment by StellaSmith** [comment]
Most of the build errors are due to treating warnings as errors with the `/WX` argument, which i think it's excessive. I propose removing that argument altogether.

**Comment by xissburg** [comment]
Sorry for not providing an update on this in over 3 months... I have tried building on Windows a while ago but I failed 😅. I decided to not spend any more time trying and moved onto more productive things. Though as I work towards wrapping up the first 1.0.0 release, this is an issue I will address soon.
