### ISSUE TITLE
Add ability to select capsule axis

### ISSUE THREAD

**Issue by qhdwight** [xissburg/edyn#92]
Proposition:

```cpp
struct capsule_shape {
    scalar radius;
    scalar half_length;
    vector3 axis;
}
```

I noticed by default it is x-axis only.

**Comment by qhdwight** [comment]
I'm also willing to make a PR for this if you'd like :)

**Comment by xissburg** [comment]
I think the axis should just be one of the 3 coordinate axes, not an arbitrary vector.

**Comment by qhdwight** [comment]
I agree, I suppose any other rotation can be obtained by changing the `orientation` component
